import type {
  Counselor, EventItem, BlogPost, Testimonial,
  Assessment, Faq, NdFact,
} from "./types";

export const counselors: Counselor[] = [
  {
    id: "sarah-m",
    name: "Dr. Sarah Meier",
    title: "ADHD Coach & Psychologist",
    canton: "Zürich (ZH)",
    languages: ["English", "German"],
    specialties: ["ADHD", "Executive Function", "Late Diagnosis"],
    modes: ["In-person", "Online"],
    rate: "CHF 160/hr",
    accepting: true,
    years: 8,
    bio: "Sarah is a licensed psychologist who was diagnosed with ADHD at 34. She brings both clinical expertise and lived experience to her work, specialising in adults navigating late diagnosis and workplace challenges.",
    approach: "I believe coaching should feel collaborative, not corrective. We'll work together to understand how your brain works best — not to fix you, but to build a life that actually fits.",
    credentials: ["MSc Clinical Psychology, UZH", "NSNS Accredited Coach", "ADHD-Europe Trained"],
    avatarTint: "teal",
    photo: "/assets/coaches/carolina.jpg",
  },
  {
    id: "thomas-w",
    name: "Thomas Wenger",
    title: "Autism Peer Mentor",
    canton: "Bern (BE)",
    languages: ["German", "French"],
    specialties: ["Autism", "Sensory Regulation", "Social Strategies"],
    modes: ["In-person", "Online", "Hybrid"],
    rate: "CHF 120/hr",
    accepting: true,
    years: 4,
    bio: "Thomas is an autistic peer mentor with a background in engineering. He works with adults and older teens on the practical side of autistic life in Swiss workplaces and communities.",
    approach: "Peer mentoring means I've been where you are. We talk honestly, we take breaks when we need to, and we build strategies that actually fit your life — not a textbook version of it.",
    credentials: ["NSNS Accredited Peer Mentor", "Autisme Suisse Certified"],
    avatarTint: "purple",
    photo: "/assets/coaches/jens.jpg",
  },
  {
    id: "amina-b",
    name: "Amina Bischof",
    title: "Neurodiversity & Relationships Coach",
    canton: "Genève (GE)",
    languages: ["French", "English", "Arabic"],
    specialties: ["Relationships", "AuDHD", "Communication"],
    modes: ["Online"],
    rate: "CHF 180/hr",
    accepting: false,
    years: 11,
    bio: "Amina specialises in neurodivergent relationships — couples, families, and the friendship systems that hold us up. She draws on systemic family therapy and her own AuDHD experience.",
    approach: "Relationships look different when our nervous systems are different. My work is about translation — helping people who love each other understand how each other's minds actually work.",
    credentials: ["Systemic Family Therapy Certified", "NSNS Accredited Coach"],
    avatarTint: "teal",
    photo: "/assets/coaches/chantal.jpg",
  },
  {
    id: "lukas-h",
    name: "Lukas Hartmann",
    title: "Workplace & Career Coach",
    canton: "Basel (BS)",
    languages: ["German", "English"],
    specialties: ["Workplace", "Career Change", "Disclosure"],
    modes: ["In-person", "Online"],
    rate: "CHF 150/hr",
    accepting: true,
    years: 6,
    bio: "Lukas helps neurodivergent professionals navigate Swiss workplace culture — from deciding whether to disclose, to requesting accommodations, to career pivots that play to your strengths.",
    approach: "Your neurodivergence isn't a career problem to manage. Done right, it's the thing that makes you extraordinary at specific kinds of work. My job is to help you find and shape those roles.",
    credentials: ["NSNS Accredited Coach", "ICF Certified"],
    avatarTint: "purple",
  },
  {
    id: "priya-k",
    name: "Dr. Priya Keller",
    title: "Post-Diagnosis Support Specialist",
    canton: "Vaud (VD)",
    languages: ["English", "French", "Hindi"],
    specialties: ["Post-Diagnosis", "Identity", "Family"],
    modes: ["In-person", "Online", "Hybrid"],
    rate: "CHF 170/hr",
    accepting: true,
    years: 9,
    bio: "Priya works with adults in the months and years following a neurodivergence diagnosis. She holds space for the grief, the relief, and everything in between.",
    approach: "A diagnosis in adulthood rewrites your whole story — childhood memories, past relationships, the jobs that nearly broke you. We give all of that the time it needs.",
    credentials: ["PhD Psychology, EPFL", "NSNS Accredited Coach"],
    avatarTint: "teal",
    photo: "/assets/coaches/susan.jpg",
  },
  {
    id: "marco-r",
    name: "Marco Rossi",
    title: "ADHD & Executive Function Coach",
    canton: "Ticino (TI)",
    languages: ["Italian", "English", "German"],
    specialties: ["ADHD", "Students", "Executive Function"],
    modes: ["Online"],
    rate: "CHF 110/hr",
    accepting: true,
    years: 3,
    bio: "Marco is the only Italian-speaking ADHD coach in the NSNS network. He works with students and young professionals across Ticino and the wider Italian-speaking community.",
    approach: "I keep it practical. We build systems that you'll actually use on a Tuesday morning when everything's gone sideways — not perfect systems, sustainable ones.",
    credentials: ["NSNS Accredited Coach", "ADDCA Certified"],
    avatarTint: "purple",
  },
  {
    id: "elena-v",
    name: "Elena Vogt",
    title: "Autism Coach — Women & Nonbinary",
    canton: "Zürich (ZH)",
    languages: ["German", "English"],
    specialties: ["Autism", "Women & Nonbinary", "Masking"],
    modes: ["In-person", "Online"],
    rate: "CHF 165/hr",
    accepting: true,
    years: 7,
    bio: "Elena specialises in autistic women and nonbinary adults — a group whose autism is often recognised late or not at all. Her practice draws deeply on the unmasking literature.",
    approach: "So many of the people I work with have spent decades performing a version of themselves. Coaching is where we figure out what's left when the performance stops — and it's usually wonderful.",
    credentials: ["MSc Psychology, UZH", "NSNS Accredited Coach"],
    avatarTint: "purple",
    photo: "/assets/coaches/samantha.jpg",
  },
  {
    id: "david-s",
    name: "David Steiner",
    title: "Teen & Young Adult Coach",
    canton: "Luzern (LU)",
    languages: ["German", "English"],
    specialties: ["Teens", "Young Adults", "Transitions"],
    modes: ["In-person", "Hybrid"],
    rate: "CHF 130/hr",
    accepting: true,
    years: 5,
    bio: "David works with neurodivergent teens and young adults navigating school-to-apprenticeship, apprenticeship-to-career, and the often-bumpy transition into adult life.",
    approach: "The jump from school to 'real life' is hard for everyone — and it's an entirely different challenge when your brain works differently. We take it in manageable pieces.",
    credentials: ["NSNS Accredited Coach", "Jugendarbeit Trained"],
    avatarTint: "teal",
  },
  {
    id: "yuki-t",
    name: "Yuki Tanaka",
    title: "Sensory & Somatic Coach",
    canton: "Vaud (VD)",
    languages: ["English", "French", "Japanese"],
    specialties: ["Sensory", "Burnout", "Somatic"],
    modes: ["In-person", "Online"],
    rate: "CHF 155/hr",
    accepting: false,
    years: 6,
    bio: "Yuki integrates somatic practice with neurodivergence coaching. Her work is especially suited to people recovering from autistic burnout or sensory overwhelm.",
    approach: "Your body has been telling you things. My work starts with listening — then we build a life that your nervous system can actually live inside.",
    credentials: ["Somatic Experiencing Practitioner", "NSNS Accredited Coach"],
    avatarTint: "teal",
    photo: "/assets/coaches/stefanie.jpg",
  },
  {
    id: "fabienne-l",
    name: "Fabienne Lemaire",
    title: "AuDHD & Life Transitions",
    canton: "Neuchâtel (NE)",
    languages: ["French", "English"],
    specialties: ["AuDHD", "Life Transitions", "Parenthood"],
    modes: ["Online", "Hybrid"],
    rate: "CHF 145/hr",
    accepting: true,
    years: 4,
    bio: "Fabienne works with people whose lives have been turned inside out by a late AuDHD diagnosis — often alongside new parenthood, career shifts, or relationship change.",
    approach: "Transitions are when old coping strategies stop working. That's not failure — it's information. We use it to build what comes next.",
    credentials: ["NSNS Accredited Coach"],
    avatarTint: "purple",
    photo: "/assets/coaches/jane.jpg",
  },
  {
    id: "samir-a",
    name: "Samir Ahmadi",
    title: "Group Facilitator & Coach",
    canton: "Aargau (AG)",
    languages: ["German", "English", "Farsi"],
    specialties: ["Group Work", "Community", "ADHD"],
    modes: ["In-person", "Online"],
    rate: "CHF 125/hr",
    accepting: true,
    years: 5,
    bio: "Samir runs NSNS peer groups and works one-to-one with ADHDers who thrive in community. His group format has a waiting list and runs in German and English.",
    approach: "A lot of what's hard about ADHD eases when you're in a room full of people whose brains work similarly. Group isn't therapy — it's learning together.",
    credentials: ["Group Facilitation Certified", "NSNS Accredited Coach"],
    avatarTint: "teal",
  },
  {
    id: "clara-n",
    name: "Clara Nydegger",
    title: "Parents of Neurodivergent Children",
    canton: "St. Gallen (SG)",
    languages: ["German", "English"],
    specialties: ["Parents", "Family", "School Navigation"],
    modes: ["In-person", "Online"],
    rate: "CHF 140/hr",
    accepting: true,
    years: 10,
    bio: "Clara supports parents of neurodivergent children — often parents who are themselves neurodivergent. She's fluent in navigating the Swiss school and diagnostic system.",
    approach: "Parents of neurodivergent kids do about three jobs at once. My work is to take some of that weight, and help you advocate without burning out.",
    credentials: ["Family Systems Certified", "NSNS Accredited Coach"],
    avatarTint: "purple",
    photo: "/assets/coaches/portrait-flowerscarf.jpg",
  },
];

export const events: EventItem[] = [
  {
    date: "2026-05-14",
    time: "18:30 – 20:30",
    title: "Late Diagnosis: Lived Experience Evening",
    location: "Zürich — Langstrasse 84",
    format: "In person",
    price: "CHF 25",
    capacity: "Limited to 24",
    description: "An informal evening for people diagnosed with ADHD or autism as adults. Three short talks, a long break, and a quiet hour for those who want to stay. Soft lighting, fidget-friendly, no forced sharing.",
    tag: "Community",
  },
  {
    date: "2026-05-22",
    time: "12:30 – 13:30",
    title: "Workplace Disclosure — A Lunchtime Clinic",
    location: "Online (Zoom)",
    format: "Online",
    price: "Free",
    capacity: "Open",
    description: "A 60-minute drop-in with Lukas Hartmann answering the disclosure questions that don't have clean answers. Bring your lunch. Cameras optional.",
    tag: "Workplace",
  },
  {
    date: "2026-06-07",
    time: "10:00 – 16:00",
    title: "Sensory-Safe Saturday: Spring Edition",
    location: "Genève — Parc La Grange",
    format: "In person",
    price: "Free / Donation",
    capacity: "Drop-in",
    description: "Our quarterly outdoor gathering. Quiet zones, loud zones, a snack table, and nothing you have to do. Bring a blanket, bring your people, bring your dog.",
    tag: "Community",
  },
  {
    date: "2026-06-19",
    time: "19:00 – 20:30",
    title: "Parents' Circle — End of School Year",
    location: "Online (Zoom)",
    format: "Online",
    price: "CHF 10",
    capacity: "8–14 people",
    description: "The end of the Swiss school year is a lot. This is a facilitated space to compare notes, decompress, and plan for summer with Clara Nydegger.",
    tag: "Family",
  },
];

export const blog: BlogPost[] = [
  {
    slug: "after-a-late-diagnosis",
    title: "After a late diagnosis: the six months nobody warns you about",
    author: "Dr. Priya Keller",
    date: "2026-04-02",
    readTime: "8 min",
    tag: "Lived Experience",
    excerpt: "The relief comes first. Then, often, something stranger — a grief for the child nobody saw, the career that didn't fit, the friend you lost. Here is what we've learned about moving through it.",
    imageTone: "teal",
    image: "/assets/blog/after-a-late-diagnosis.jpg",
  },
  {
    slug: "sensory-loads-and-swiss-winters",
    title: "Sensory loads and Swiss winters",
    author: "Yuki Tanaka",
    date: "2026-03-18",
    readTime: "5 min",
    tag: "Wellbeing",
    excerpt: "Heated trams, dry indoor air, end-of-winter daylight — a practical guide to the sensory micro-stressors of Swiss February and what actually helps.",
    imageTone: "purple",
    image: "/assets/blog/sensory-loads-and-swiss-winters.jpg",
  },
  {
    slug: "the-unexpected-grace-of-routines",
    title: "The unexpected grace of routines",
    author: "Sarah Meier",
    date: "2026-02-28",
    readTime: "6 min",
    tag: "Strategies",
    excerpt: "For a long time I thought routines were prisons. Now I think of them as a kind of care — a way of being kind to my future self at a time of day when she isn't coping.",
    imageTone: "warm",
    image: "/assets/blog/the-unexpected-grace-of-routines.jpg",
  },
  {
    slug: "coaching-isnt-fixing",
    title: "Coaching isn't fixing",
    author: "NSNS Editorial",
    date: "2026-02-11",
    readTime: "4 min",
    tag: "About Coaching",
    excerpt: "A short piece on what the word 'coaching' means in a neurodiversity context — and, more importantly, what it shouldn't mean.",
    imageTone: "teal",
    image: "/assets/blog/coaching-isnt-fixing.jpg",
  },
  {
    slug: "autism-women-nonbinary",
    title: "What autism looks like when nobody is looking for it",
    author: "Elena Vogt",
    date: "2026-01-22",
    readTime: "9 min",
    tag: "Autism",
    excerpt: "Most diagnostic criteria were written about boys. This piece is about what autism actually looks like in women and nonbinary adults, and why it takes so long to find.",
    imageTone: "purple",
    image: "/assets/blog/autism-women-nonbinary.jpg",
  },
  {
    slug: "a-letter-to-the-freshly-diagnosed",
    title: "A letter to the freshly diagnosed",
    author: "NSNS Community",
    date: "2026-01-08",
    readTime: "3 min",
    tag: "Lived Experience",
    excerpt: "Twelve sentences from twelve people who've been where you are. Save it for the hard days.",
    imageTone: "warm",
    image: "/assets/blog/a-letter-to-the-freshly-diagnosed.jpg",
  },
];

export const testimonials: Testimonial[] = [
  {
    name: "Mira, 37",
    location: "Zürich",
    quote: "I spent twenty years thinking I was bad at life. Three months with my NSNS coach, and I understood that the life I'd been handed just wasn't built for my brain. That reframe changed everything.",
  },
  {
    name: "Julien, 29",
    location: "Lausanne",
    quote: "The assessment process was the first time a professional had ever listened to me without trying to make me smaller. I came out with a diagnosis, but also with a kind of peace I hadn't felt since I was a child.",
  },
  {
    name: "Anna & Ben",
    location: "Bern",
    quote: "We thought our son's school problems were our fault. NSNS helped us see they were a system problem — and showed us how to advocate for him without burning ourselves out.",
  },
];

export const assessments: Assessment[] = [
  {
    id: "adhd",
    name: "ADHD Assessment",
    duration: "3–4 sessions",
    price: "CHF 1,900 – 2,400",
    overview: "A structured adult ADHD evaluation drawing on the DIVA-5, self-report inventories, collateral interview, and an extended clinical conversation.",
    includes: [
      "Initial 90-min clinical interview",
      "DIVA-5 structured interview",
      "Self-report inventories (ASRS, CAARS, WURS)",
      "Collateral interview with a person who knew you in childhood",
      "Written report with diagnostic formulation",
      "60-min feedback session",
    ],
    colour: "teal",
  },
  {
    id: "autism",
    name: "Autism Assessment",
    duration: "4–5 sessions",
    price: "CHF 2,400 – 3,200",
    overview: "A full adult autism assessment using ADOS-2 and ADI-R alongside a rich clinical interview. Designed to be sensitive to masking, late recognition, and the adult presentation of autism.",
    includes: [
      "Initial 90-min intake",
      "ADOS-2 structured observation",
      "ADI-R developmental interview",
      "Sensory profile and masking inventory",
      "Written report with diagnostic formulation",
      "Two follow-up feedback sessions",
    ],
    colour: "purple",
  },
  {
    id: "combined",
    name: "Combined AuDHD",
    duration: "5–6 sessions",
    price: "CHF 3,200 – 4,200",
    overview: "For adults who suspect both ADHD and autism. We take the time to look at both in parallel — because the overlap matters, and neither assessment alone tells the full story.",
    includes: [
      "Everything in the ADHD and Autism pathways",
      "Co-occurrence analysis",
      "Integrated report and formulation",
      "Three follow-up feedback sessions",
      "Optional coaching referral within network",
    ],
    colour: "warm",
  },
];

export const assessmentFaqs: Faq[] = [
  { q: "Why do private assessments cost what they do?", a: "A thorough adult assessment is 12 to 20 hours of clinical time plus report writing. Our prices reflect the real hours involved, at fair rates for Swiss-licensed clinicians. Sliding-scale places are available on request." },
  { q: "Will my insurance cover this?", a: "Some basic insurance plans cover assessment partially if referred by a GP. Supplementary insurance often covers more. We'll help you check during intake and provide the paperwork you'll need." },
  { q: "How long is the waiting list?", a: "Currently 8–14 weeks depending on language and clinician. We prioritise urgent situations (workplace, education, mental-health-adjacent) where we can." },
  { q: "Can I just do the assessment, and not the coaching?", a: "Absolutely. Many of our clients come for assessment only, and we're careful not to pressure anyone into ongoing services. If you ever want coaching support later, our network will still be here." },
  { q: "What if I don't get a diagnosis?", a: "That's a real and normal outcome. A thorough assessment is useful whether or not you meet diagnostic threshold — you'll leave with a much clearer picture of yourself either way." },
];

export const positiveMessages: string[] = [
  "Your brain is not a problem to be solved. It is a way of being.",
  "Rest is not a reward. It's a need.",
  "The world is slowly learning to expect you. You are allowed to take up space.",
  "Masking is survival, not character. You are allowed to stop when it's safe.",
  "Your sensory needs are real. Trust your nervous system.",
  "Diagnosis is a door, not a verdict.",
];

export const ndFacts: NdFact[] = [
  { stat: "~15–20%", label: "of people are estimated to be neurodivergent in some way" },
  { stat: "5–8 years", label: "average delay between first seeking help and diagnosis in adulthood" },
  { stat: "2/3", label: "of autistic adults in Switzerland report unmet support needs" },
  { stat: "1 in 20", label: "adults have ADHD — most still undiagnosed" },
];
